Added Traditional Chinese (zh_tw.json)
Patbox/UniversalShops pull request #30
Opened 2024-07-19 17:56 UTC by yichifauzi

Added Traditional Chinese translation

2024-07-21 08:57 UTC, notlin4 requested changes

2024-07-21 08:57 UTC, notlin4 commented on src/main/resources/data/universal_shops/lang/zh_tw.json
> +  "gui.universal_shops.setup.cant_change_pricehandler.1": "無法更改此設定！",
```suggestion
  "gui.universal_shops.setup.cant_change_pricehandler.1": "無法變更這項設定！",
```

2024-07-21 08:57 UTC, notlin4 commented on src/main/resources/data/universal_shops/lang/zh_tw.json
> +  "gui.universal_shops.click_to_buy": "點擊物品購買",
```suggestion
  "gui.universal_shops.click_to_buy": "按物品以購買",
```

2024-07-21 08:57 UTC, notlin4 commented on src/main/resources/data/universal_shops/lang/zh_tw.json
> +  "gui.universal_shops.setup.click_to_change_mode.1": "點擊以更改模式",
```suggestion
  "gui.universal_shops.setup.click_to_change_mode.1": "按這裡變更模式",
```

2024-07-21 08:57 UTC, notlin4 commented on src/main/resources/data/universal_shops/lang/zh_tw.json
> +  "gui.universal_shops.setup.click_to_change_mode.2": "按住 Shift 鍵向後更改",
```suggestion
  "gui.universal_shops.setup.click_to_change_mode.2": "按住 Shift 鍵向後變更",
```

2024-07-21 08:57 UTC, notlin4 commented on src/main/resources/data/universal_shops/lang/zh_tw.json
> +  "gui.universal_shops.modifying_item.change_item": "更改基本物品",
```suggestion
  "gui.universal_shops.modifying_item.change_item": "變更基本物品",
```

2024-07-21 08:57 UTC, notlin4 commented on src/main/resources/data/universal_shops/lang/zh_tw.json
> +  "text.universal_shops.requires_setup_by_owner": "此商店尚未設定！",
```suggestion
  "text.universal_shops.requires_setup_by_owner": "這個商店尚未設定！",
```

2024-07-21 08:57 UTC, notlin4 commented on src/main/resources/data/universal_shops/lang/zh_tw.json
> +  "hologram_type.universal_shops.disabled": "停用",
```suggestion
  "hologram_type.universal_shops.disabled": "已停用",
```

2024-07-21 08:57 UTC, notlin4 commented on src/main/resources/data/universal_shops/lang/zh_tw.json
> +  "gui.universal_shops.virtual_balance.selected_account": "已選帳戶：%s",
```suggestion
  "gui.universal_shops.virtual_balance.selected_account": "已選擇帳戶：%s",
```

2024-07-21 08:57 UTC, notlin4 commented on src/main/resources/data/universal_shops/lang/zh_tw.json
> +  "gui.universal_shops.virtual_balance.cost.title": "更改價格",
```suggestion
  "gui.universal_shops.virtual_balance.cost.title": "變更價格",
```

2024-08-10 08:28 UTC, notlin4 approved these changes

2024-08-10 15:26 UTC, Patbox commented
Hey! Translations should be sent via https://crowdin.com/project/patbox-mods as it makes things simple. Sorry for not responding to about this!

2024-08-10 17:07 UTC, yichifauzi commented
> Hey! Translations should be sent via https://crowdin.com/project/patbox-mods as it makes things simple. Sorry for not responding to about this!

Already submitted please check it Patbox thanks you for making this mod

2024-09-15 11:53 UTC, closed without merging